### PR TITLE
46.recovery

### PR DESCRIPTION
**Pull request by YufengXin**
@sajith I restructured the pce code a little bit in which I created a new "simulation" sub fold where I moved all the 'research/simulation' scripts/examples into. They are not used in sdx operation. This is a precursory to my next commit addressing protection TE optimization that would happen later.

I rebased it on the current main. I am somehow puzzled by GitHub saying it's '100 commits behind main'. Maybe I used the git command incorrectly.

Please review and make sure it doesn't affect anything running.  Thanks.

### CODE REVIEW

**Comment by YufengXin** [comment]
@sajith never mind. I will resolve the problems first, then ask you to review again.

**Comment by YufengXin** [comment]
I think I should wait after you tag the main to 2.1.0 as you planned.

**Comment by sajith** [comment]
@YufengXin I don't think you need to hold this off, because the new code does not alter existing PCE APIs.  You should be able to do something like this:

```console
$ git fetch origin
$ git merge origin/main -m "merge main"
$ pip install black isort tox
$ black .   # format code
$ isort .   # sort imports
$ tox       # run tests
```

If everything goes well, update this branch, and then re-open this PR:

```
$ git push origin 46.recovery
```

That should work, from my quick testing.  Please let me know if you need anything else.

**Comment by YufengXin** [comment]
Sure. I'll work on it. thanks.

BTW, this instruction should go to that "DeveloperGuidance" doc. -:) I used to use "git rebase", I'll start to use git merge.....

**Comment by sajith** [comment]
When working with Git and GitHub, there are many non-obvious things to try when things do not go as expected.  It is usually better to follow Git or GitHub documentation, than trying to document it ourselves.  

GitHub's PR diffs (sometimes? always?) seem confusing when using `git rebase`.  I do not know why.  So I just do `git merge master`.

As for other things (code formatting and testing), yes, we should get that stuff documented!

**Pull request closed without merging**
