### PR TITLE
22 objective function

### PR DESCRIPTION
**Pull request by YufengXin**
complete implementation of PCE functions with an example unites in tests.LoadBalancing.test_te_solver.
This leaves the previous implementation (classes and functions) untouched. 

#22 #45 #47 #48 can bed closed after this.

### CODE REVIEW

**Comment by sajith** [comment]
I am yet to review this, but I do have a suggestion to make. 

This is a pretty big set of changes, and therefore it is very hard to review.  We should aim to make smaller changes at a time, and more frequently.  That way PRs will be easier to understand, review, and merge, and we all will have a better idea about the changes.

**Comment by YufengXin** [comment]
Agreed and will do. You can treat this PR the kind of 'first' as most of the codes are new first-time. Part of the purpose is to trigger the CI test. After this, we'll do minor PRs.

**Comment by sajith** [comment]
> Agreed and will do. You can treat this PR the kind of 'first' as most of the codes are new first-time. Part of the purpose is to trigger the CI test. After this, we'll do minor PRs.

Okay, working on this.

**Comment by sajith** [comment]
I've pushed a couple of commits to this branch which should address our issues with test jobs on GitHub Actions: 

 - Dropped Python 3.7 from the test matrix, and
 - Let all jobs run to completion instead of letting one failing job cancel all the others.  Now we should get a little more useful feedback from CI.

There are other failures from the actual running of tests now, but I guess they are yours, @YufengXin. :-)

**Review by sajith — APPROVED** [review]
Thanks!  I have left a bunch of comments inline.  Surely I must have missed many things, considering that this is a pretty big set of changes. :-)

Some general comments:

- We seem to be opening some JSON files without sufficient error checking.  We're making some assumptions about the location of those files which won't hold true when the library is installed.  It would be ideal for library functions to avoid file I/O: such functions are hard to reason about, and they're rather brittle.  If we must do file I/O, we should document our reasons for doing so.

- We have many `print()` statements throughout. It is better to avoid them, and use logging. That way clients get to have more flexibility as to what to log and how.

- Docstrings at the module, class, function level would be very useful for our own future selves, and for any other future readers of the code.

- [PEP 8](https://peps.python.org/pep-0008/) standardizes naming (of modules, classes, functions, variables) in Python. For readability's sake, it would be a good idea to follow those suggestions. To quote a wise person: “Programs must be written for people to read, and only incidentally for machines to execute.”

- Using [f-strings](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals) to format strings is nicer.

- It is not clear which functions are meant to be private to a class -- it would be useful to use the conventional `_` prefix.

- pydot is a test dependency.  We should add it to `test-requirements.txt` or similar, and update README accordingly.

- One test is not passing for me: 

```python
FAILED tests/LoadBalancing/test_HeurCSP_Solver.py::Test_HeurCSP_Solver::test_Computation - AssertionError: [{'1': [[1, 9], [9, 11]], '2': [[3, 1], [[78 chars]98.0] != <Heuristic.Heur_CSP.TE_Group_Heur object [13 chars]bd30>
```

Regarding naming and docstrings and other linter checks, we should be using flake8 in a stricter manner to catch them at CI.  Right now we're just ignoring them, but we need to have a plan to make the checks stricter.

With adequate docstrings, we could also have Sphinx-generated documentation.

Please address (or ignore!) the review comments at your convenience, on this PR or on subsequent PRs.  It would be useful to have issues for the things meant to be addressed later.  Regardless, please make sure that the tests pass on this PR.

**Comment by sajith** [comment]
Another thought: we should extend the test coverage to ensure that we test failure cases also.  It would be useful to have a coveralls report; I'll work on that. (This is issue #42, and I can resolve that, now that I have access to this repo's settings.)

**Comment by sajith** [comment]
@YufengXin Regarding [this](https://github.com/atlanticwave-sdx/pce/actions/runs/3463150449) test failure on CI:

```python
tests/LoadBalancing/test_HeurCSP_Solver.py:4: in <module>
    from Heuristic.Heur_CSP import Heuristic_CSP
E   ModuleNotFoundError: No module named 'Heuristic.Heur_CSP'
```

That happens because `src/Heuristic/Heur_CSP.py` was [deleted](https://github.com/atlanticwave-sdx/pce/pull/50/commits/d7e0fac2d30b19ad75efc688c7b22c3f9fa1a38b#diff-647d382f56aa01a69ecbc63704a2993b0206f73db452ba9d974541a7b333659d).  We could either delete the test also, or adapt it to test `Heuristic.Heur.py`?

**Pull request merged**
