### PR TITLE
Handle several connection requests in TEManager

### LINKED ISSUE #158: Handle more than one connection request
At present `TEManager` is instantiated like so:

```python
    temanager = TEManager(topology_data, connection_request)
```

We do not have a way of adding different subsequent connection requests.  TEManager should be able to deal with concurrent connection requests and release requests, not just one.

Related to #122.  PR #156 adds some tests for VLAN assignments, but they exercise VLAN assignments by repeatedly issuing the same connection request.

### PR DESCRIPTION
**Pull request by sajith**
Fixes #158.  Changes:

- Overhaul `TEManager` class such that `TEManager(topology_data, connection_request)` is changed to `TEManager(topology_data)`.
- Change `generate_connection_te()` to `generate_connection_matrix(traffic_request)` - now this method takes a connection request, not `TEManager` constructor.
- Update and add some tests accordingly.
- Add a test that uses two distinct connection requests.

### CODE REVIEW

**Comment by YufengXin** [comment]
Cool. Just one thing: between provisioning two consecutive requests, there is a need to update the available bandwidth on the links being used by the first request. There was a .update_graph() function for this purpose.

**Comment by YufengXin** [comment]
For the test case: test_connection_amlight_to_zaoxi_two_identical_requests()

**Comment by sajith** [comment]
Ah yes, good catch.  It might be simpler to address that in a separate step. I will create an issue.

**Comment by sajith** [comment]
Let us track bandwith assignment in https://github.com/atlanticwave-sdx/pce/issues/162.

**Review by YufengXin — APPROVED** [review]

**Pull request merged**
