### PR TITLE
67.script

### PR DESCRIPTION
**Pull request by YufengXin**
1. Put simulation scripts to the scripts subfolder.
2. Pushed in the heur.py for group based heuristics
3. removed a few unused functions from the random_connection_generatoer

4. (only) Did a few DocString in TESolver

### CODE REVIEW

**Comment by sajith** [comment]
@YufengXin From the [diff](https://github.com/atlanticwave-sdx/pce/pull/142/files), it looks like you did a `git rebase origin/main`. That is a confusing set of changes to look at. :-)

Can you do a `git fetch origin; git merge origin/main`?

**Comment by YufengXin** [comment]
@sajith I did the merge. Somehow, GitHub thought my local branch name is not the same as the remote, so I did a "git branch --upstream..." to fix it. Maybe that's why?

It looks easier in this PR page: the first part was my commits and the second box was the commits in main ahead of my branch.   

Basically, I didn't change the existing API. mostly changes in the new files to adapt to the main.

Now the checks are passed. Is the diff clearer to you? Otherwise I'll redo it...

**Comment by sajith** [comment]
@YufengXin I can work with this. Give me some time to study the changes. :-)

**Comment by YufengXin** [comment]
@sajith If you haven't started, let me redo it in 2 or 3 PRs-:)

**Comment by sajith** [comment]
@YufengXin Not yet. Do as you please, please!

**Comment by YufengXin** [comment]
Will redo this in multiple smaller PRs.

**Pull request closed without merging**
