### PR TITLE
Package topology data

### PR DESCRIPTION
**Pull request by sajith**
Issue is #138. Changes:

- Move the static topology files from `tests/data/topologies` to `src/sdx/pce/data/topologies`.
- Move the sample connection request from `tests/data/test_request.json` to under `src/sdx/pce/data/requests`.
- Test the topologies some more, by writing their graph representation to an image under `/tmp`.
- Drop Python 3.8 from CI (too old; [does not provide](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files) `importlib.resources.files`); add Python 3.11 instead (newer, should help us with a migration path when we need to).

The reason for this change is this: by packaging these data files, we can reuse them in some of the sdx-controller tests.  Once pce library is installed, these files can be used like so:

```python
import json
from importlib.resources import files

pce_data_dir = files("sdx.pce")  / "data"

topology_file_amlight = pce_data_dir / "topologies" / "amlight.json"
connection_req = pce_data_dir / "requests" / "test_request.json"

amlight_topology_data = json.loads(topology_file_amlight.read_text())
connection_request_data = json.loads(connection_req.read_text())
```

### CODE REVIEW

**Comment by YufengXin** [comment]
Looks nice, except the default Python in Mac is still 3.8.8

**Comment by YufengXin** [comment]
My point was actually we need to verify that Mert uses 3.9 in the testbed.

**Comment by sajith** [comment]
Yes, macOS was the reason I included Python 3.8 in the CI matrix originally. :-)

Although currently on macOS Ventura (13.4.1), `/usr/bin/python3` is 3.9.6.  On an 10+ year old Intel MacBook (which just received an OS update) I have Python 3.8.9.  I don't know about Apple's official Python support timeline, so 3.8 seems to be a reasonable baseline.  But then most people do `brew install python3` or some such so that they can use a reasonably newer Python than the system default.

You are right though.  I am reluctant to use a newer API, which is why I have not asked for a review yet.  I will try to find a way that is less dependent on minor Python version.

**Comment by sajith** [comment]
One solution to support Python 3.8 turned out to be [importlib-resources](https://importlib-resources.readthedocs.io/en/latest/).  It already is a dependency of matpolotlib (which we use), so there's not too much overhead.

**Pull request merged**
